config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  get 'new', to: 'application#new', as: 'new_post'
  post 'create', to: 'application#create', as: 'create_post'
  delete 'destroy', to: 'application#destroy', as: 'destroy_post'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @posts = Post.all
  end

  def new
  end

  def create
    @post = Post.new(post_params)
    if @post.save!
      redirect_to root_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h1>Index</h1>
<%= link_to "New", new_post_path %>
<% if !@posts.blank? %>
  <% @posts.each do |p| %>
    <div>
      <%= image_tag p.image %><br>
      <%= link_to "Delete post...", destroy_post_path(id: p.id), method: :delete, remote: true %>
    </div>
  <% end %>
<% end %>

app/views/application/new.html.erb
<h1>New</h1>

<div>
	<%= form_with scope: :post, url: create_post_path, local: true do |form| %>
    <%= form.file_field :image, direct_upload: true %>
    <%= form.submit :save %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActStorageTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>